### PR TITLE
Performance Optimization

### PR DESCRIPTION
**Pull request by chwilfing**
Multiple Changes to retrieve data from remote locations only once not multiple times.
Modify export-csv to use already retrieved data, not retrieve again.

### CODE REVIEW

**Comment by VeronicaGeek** [comment]
A few things after running your changes.
1. **Skype section:** Throw an error in the console, and Skype users are not displayed in the tool.
skypeerror

2. In the _export_ section of each workload, I tried in the past to put the variable instead of the cmdlet, but some of the .csv files are not exporting the data (_i.e.: Try your code and export the "Domains"_)
3. **Device Access Rules** Export shows more properties in the .csv file than requested.
4. Your Write-Host when retrieving the data says "policys" (should say **"policies"**) 
5. Remove the _"all"_ in your Write-Host just for consistency with the other ones _(i.e.: Retrieving users)_

**Comment by chwilfing** [comment]
Pushed a new commit plz check.

I found an issue with the Skype export even if I could not exactly reproduce your error.

**Comment by VeronicaGeek** [comment]
@chwilfing : Do you have a commit awaiting? I get an error when trying to get your code in Visual Studio, and also the "policys" are not changed.

**Comment by chwilfing** [comment]
Interesting, I made the requested changes and amended my last commit to be consistent. Maybe this is a problem? should I create another commit to update?

**Comment by VeronicaGeek** [comment]
Just make sure you push everything to your branch, and then look at the "Files changed" tab (on top) to see if this has been taken into account.

**Comment by chwilfing** [comment]
ok, i'm really just tooo stupid... i've merged the wrong way, i'll try again with another pr .. really sorry..

**Pull request closed without merging**
